### ISSUE TITLE
Old mouse wheel adjustment for mac is no longer needed

### ISSUE THREAD

**Issue by baconpaul** [steinbergmedia/vstgui#106]
Hi!

In cview.cpp you have

```
bool CView::onWheel (const CPoint& where, const CMouseWheelAxis& axis, const float& distance, const CButtonState& buttons)
{
        if (axis == kMouseWheelAxisX)
        {
                #if MAC // mac os x 10.4.x swaps the axis if the shift modifier is down
                if (!(buttons & kShift))
                #endif
                return onWheel (where, distance*-1, buttons);
        }
        return onWheel (where, distance, buttons);
}
```

but that adjustment in modern macOS (I'm on 10.14) means shift-two-finger-drag goes the wrong way.

We can adjust for this in our code no problem but I think you probably want to remove that adjustment so figured I'd share!

Thanks so much

  Paul

**Comment by scheffle** [comment]
Thanks for the hint. I came to the conclusion that the onWheel method without axis doesn't make sense anymore so I removed it on the develop branch. Only the method with the axis method is now used throughout vstgui. if you have custom views you have to adopt this change.

**Comment by baconpaul** [comment]
Ok thanks! We will adjust when we next sync up.

**Comment by baconpaul** [comment]
(Oh and yeah I agree the onwheel without axis is hard. Luckily we only have sliders not trackpads in our ui!)
