### ISSUE TITLE
Building fails on macOS 10.15 (Xcode 11.1)

### ISSUE THREAD

**Issue by ryukau** [steinbergmedia/vstgui#120]
I'm using [GitHub Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions) to build VST3 for macOS. Recently GitHub upgraded macOS virtual environment to Catalina (10.15) and vstgui starts failing to build.

CMake error:
```
[ 23%] Building CXX object vstgui4/vstgui/lib/CMakeFiles/vstgui.dir/platform/mac/caviewlayer.mm.o
/Users/runner/vst3sdk/vstgui4/vstgui/lib/platform/mac/caviewlayer.mm:83:9: error: no matching function for call to 'objc_msgSendSuper'
        self = objc_msgSendSuper (SUPER, @selector(init));
               ^~~~~~~~~~~~~~~~~
/Applications/Xcode_11.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/objc/message.h:67:1: note: candidate function not viable: requires 0 arguments, but 2 were provided
objc_msgSendSuper(void /* struct objc_super *super, SEL op, ... */ )
^
1 error generated.
make[2]: *** [vstgui4/vstgui/lib/CMakeFiles/vstgui.dir/platform/mac/caviewlayer.mm.o] Error 1
```

GitHub Actions setting:
- https://github.com/ryukau/VSTPlugins/blob/master/.github/workflows/build.yml

Build command:
- https://github.com/ryukau/VSTPlugins/blob/master/ci/ci_macos.sh

Environment:
- https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#macos-1015

**Comment by scheffle** [comment]
Building with Xcode 11.1 on macOS 10.15 works here without issue. Can you post a verbose output of the build job?

**Comment by ryukau** [comment]
Full log:
https://gist.github.com/ryukau/cf3da880b93074059d15d2e4251f0d8c

Just in case, I use following cmake option.

```bash
cmake -DCMAKE_BUILD_TYPE=Release \
  -DSMTG_MYPLUGINS_SRC_PATH="$GITHUB_WORKSPACE" \
  -DSMTG_ADD_VST3_HOSTING_SAMPLES=FALSE \
  -DSMTG_ADD_VST3_PLUGINS_SAMPLES=FALSE \
  ..
```

**Comment by scheffle** [comment]
Please use the Xcode generator when building on macOS.
`cmake -GXcode ...`
This should work.

**Comment by ryukau** [comment]
It works with `cmake -GXcode`. Thanks for the answer.
