### ISSUE TITLE
Resource path not initialized correctly

### ISSUE THREAD

**Issue by jpcima** [steinbergmedia/vstgui#129]
There is a problem of static initialization order in X11 VSTGUI.
Depending on it, the resource path may or may not be set correctly at startup, and Cairo will be able or not to load image files.

Several users of Debian buster have reported this problem.

Some more detailed discussion has occurred here on this topic.
https://github.com/sfztools/sfizz/issues/135

The following patch has been reported to work as a fix for this problem.
https://github.com/sfztools/sfizz/issues/135#issuecomment-605611835

EDIT forgot to add, this was vstgui4 from the vst-sdk_3.6.14_build-24_2019-11-29 package

**Comment by jpcima** [comment]
This problem relates to the order of static initialization.
While I don't recall the exact detail, the matter was the if order was (A,B) the resource path is good, if (B,A) it's empty and it can't load any graphics.

This behavior was dependent on the OS runtime and/or compiler used to build.
Using the debian stretch build, the users have reported success; using debian buster all have reported failure, consistently.

This was the step to reproduce the problem: build and run on debian buster.
I don't currently have the setup to recheck this problem and provide more detail, except telling that it exists.

This patch's solution consists to compute this path lazily on its first request, instead of the very start.
This is initialized inside this function `Frame::getResourcePath`.
https://github.com/sfztools/vstgui/blob/c6a7f607c21a7353e922a6d45e54d6c56d5a6745/vstgui/lib/platform/linux/x11frame.cpp#L805

**Comment by scheffle** [comment]
I welcome you to make a pull request for this issue as I'm currently not able to cleanly apply the patch and verify it. Thank you!

**Comment by scheffle** [comment]
Should be fixed with #172
