### ISSUE TITLE
[Mac] aliased text renders doubled on macOS 10.15.x

### ISSUE THREAD

**Issue by sophiapoirier** [steinbergmedia/vstgui#141]
On macOS 10.15.x, aliased text renders doubled, with one of the renders offset 1 pixel to the right, creating thick/smeared text.  I isolated the change that introduced the bug and it was when NSViewFrame::NSViewFrame added the call `nsView.layer.drawsAsynchronously = YES;`.  This bug does not occur in earlier versions of macOS nor in current betas of macOS 11, so my proposed fix is simply to avoid `drawsAsynchronously` on macOS 10.15.

```
diff --git a/vstgui/lib/platform/mac/cocoa/nsviewframe.mm b/vstgui/lib/platform/mac/cocoa/nsviewframe.mm
index c5face85..42ca6ea6 100644
--- a/vstgui/lib/platform/mac/cocoa/nsviewframe.mm
+++ b/vstgui/lib/platform/mac/cocoa/nsviewframe.mm
@@ -843,7 +843,7 @@ static id VSTGUI_NSView_makeTouchbar (id self)
 		if (systemVersion.majorVersion > 10 || (systemVersion.majorVersion >= 10 && systemVersion.minorVersion > 10))
 		{
 			[nsView setWantsLayer:YES];
-			if (systemVersion.majorVersion > 10 || (systemVersion.majorVersion >= 10 && systemVersion.minorVersion >= 13))
+			if (systemVersion.majorVersion > 10 || (systemVersion.majorVersion >= 10 && systemVersion.minorVersion >= 13 && systemVersion.minorVersion != 15))
 				nsView.layer.drawsAsynchronously = YES;
 		}
 	}
```

**Comment by raygit83** [comment]
> 
> 
> I just checked and you can already do this at runtime:
> 
> ```
> #include "vstgui/lib/platform/platform_macos.h"
> 
> if (auto cocoaFrame = dynamic_cast<ICocoaPlatformFrame*> (frame->getPlatformFrame ()))
> {
> cocoaFrame->getNSView ().layer.drawsAsynchronously = NO;
> }
> ```
> 
> I think this should work. Can you verify?

What if the .drawsAsynchronously field isn't available in the nslayer layout, i.e. don't I need to ensure that we're running on >=10.13 before executing this code like it's done in nsviewframe when setting the drawsAsynchronously field?

**Comment by raygit83** [comment]
Hi,

here's something else related to your discussion. The following code requires ObjC, so it requires a separate .mm file:

```
#include "vstgui/lib/platform/platform_macos.h"

if (auto cocoaFrame = dynamic_cast<ICocoaPlatformFrame*> (frame->getPlatformFrame ()))
{
cocoaFrame->getNSView ().layer.drawsAsynchronously = NO;
}
```
Given that `nsView.layer.drawsAsynchronously = YES;` causes issues (red glitches, lagging GUI updates) on some systems, what about adding an extra useAsyncLayerDrawing() function to CocoaFrame, so it can be easily configured in the client code.

Also, the Apple developer documentation states _"However, you should always measure the actual performance benefits before enabling this capability."_ so I think we should be able to configure this easily and out of the box.

**Comment by scheffle** [comment]
In the next version there will be an easy way to turn this on or off. See https://github.com/steinbergmedia/vstgui/blob/develop/vstgui/lib/platform/mac/macfactory.h#L22

**Comment by raygit83** [comment]
> 
> 
> In the next version there will be an easy way to turn this on or off. See https://github.com/steinbergmedia/vstgui/blob/develop/vstgui/lib/platform/mac/macfactory.h#L22

Ah, that's good to know. Thanks for your feedback. Do you think this can be implemented in a way that it can be toggled without having to re-instanciate or to close/re-open the frame?
