### ISSUE TITLE
VSTGUIEditor: kDefaultNative is not a member of VSTGUI

### ISSUE THREAD

**Issue by jpcima** [steinbergmedia/vstgui#165]
Hi, it's no longer possible to use current `develop` with `VSTGUIEditor` from vst3_public_sdk.
I believe the `enum class` modification broke it at commit 1490ad5.

The location of the error in VST3:
https://github.com/steinbergmedia/vst3_public_sdk/blob/a395ed998bfee1969d623c15a5825160de7fd32c/source/vst/vstguieditor.h#L69

**Comment by scheffle** [comment]
Will be fixed in the next VST SDK.

**Comment by jpcima** [comment]
OK I'll wait, thanks
