### ISSUE TITLE
Double click on a control makes the mouse sticky (Linux only).

### ISSUE THREAD

**Issue by rehans** [steinbergmedia/vstgui#18]
I have some knobs and when I double click on them the mouse becomes sticky to them. So if I hover a knob without prior clicking on it, the knob still turns.

It seems as if the double (or even tripple) click event in GtkFrame::on_button_press_event (x11frame.cpp) is not handled correctly.

The documentation lists the sequence of events: 
https://developer.gnome.org/gdk3/stable/gdk3-Event-Structures.html#GdkEventButton

**Comment by scheffle** [comment]
This should now be fixed with 2ac1d55530c9b82fb0da0b934caf8688a1d38011.
