### ISSUE TITLE
VSTGUI Standalone Editor Menu Bug

### ISSUE THREAD

**Issue by simonhochrein** [steinbergmedia/vstgui#182]
When using the vstgui editor on a standalone project, I can click the edit menu, but the file menu seems to do nothing. I examined the code and was unable to determine the cause. Any help would be appreciated.

**Comment by scheffle** [comment]
The file menu has no entries in standalone mode. Why do you want to access it?

**Comment by simonhochrein** [comment]
I am attempting to save the results after editing the UI. Is there a better way to do this?

**Comment by scheffle** [comment]
It will be saved automatically when you close the editor.

**Comment by simonhochrein** [comment]
Oh, thanks! I figured I was missing something. Is this documented?

**Comment by scheffle** [comment]
No, the standalone editing part is not documented yet.
