### ISSUE TITLE
Font baselineline height is not cross platform

### ISSUE THREAD

**Issue by mxa** [steinbergmedia/vstgui#191]
The font baseline is offset on different platforms.
On MacOS the font sits significantly higher than on Linux. This becomes apparent at big fontsizes. Use a font with a size of 100 for testing. Size matches perfectly, also the horizontal positioning, just the vertical dimension of the baseline is off. 
(Kerning is not pixel-perfect either, but that's sadly to be expected).

**Comment by mxa** [comment]
Thanks for fixing. What's the roadmap for this to be released? It turns out to be quite difficult to cherry pick this one and integrate it into the current vst3sdk without other kinds of things to break.

**Comment by scheffle** [comment]
This will be released with the next vstsdk update.

**Comment by mxa** [comment]
With the newly released vstsdk the font baselines of Linux and MacOS match up, but on Windows a font with a size of 92 is about 15px elevated relative to the  other platforms. Please reopen the issue.

**Comment by jpcima** [comment]
I confirm, there is definitely vertical text offset problems on Windows OS.
Back in the pango PR, I posted the picture below as an example.

I don't have Windows running at the moment, but I can describe situation as follows:
when the label below contains the unicode musical sharp symbol (1), and when it doesn't (2):
the text gets displayed on a different base line, and so the text "jumps" when it switches.

![Capture d’écran_2021-02-26_14-56-56](https://user-images.githubusercontent.com/17614485/109308879-e334e000-7842-11eb-9387-973552f6fbe9.png)

**Comment by scheffle** [comment]
@mxa - There's no change on the Windows side in the last versions. Please make a new entry with example screenshots. Thanks.

**Comment by mxa** [comment]
> @mxa - There's no change on the Windows side in the last versions. Please make a new entry with example screenshots. Thanks.

OK, will do that next time I boot the windows box.

**Comment by mxa** [comment]
Opened a new issue https://github.com/steinbergmedia/vstgui/issues/207
