### ISSUE TITLE
Bug in D2DFont::GetMetric

### ISSUE THREAD

**Issue by JonHodgson** [steinbergmedia/vstgui#20]
After installing a couple of LilyPond GUI editors (Denemo and Frescobaldi) I found that some elements on my plugin UIs were seriously messed up, especially in the UI editor.

Further investigation revealed that the results from GrtMetric were very odd indeed.
 
In turns out that the problem was here

		if (fontCollection)
		{
			IDWriteFontFamily* fontFamily = 0;
			fontCollection->GetFontFamily (0, &fontFamily);

This code assumes that the first fontfamily in the collection is the one we want. This is not necessarily the case. Now normally we don't notice, because fonts have vaguely similar metrics, but one of the apps I had installed installed the feta26 font, which is not a text font but a set of musical notation synbols, and has very unusual metrics, so that difference was very visible.

The solutiom is to first find the correct font family, the following appears to work

		if (fontCollection)
		{
			UINT32 fontFamilyIndex;
			BOOL fontFamilyExists;
			fontCollection->FindFamilyName(nameStr, &fontFamilyIndex, &fontFamilyExists);
			IDWriteFontFamily* fontFamily = 0;
			fontCollection->GetFontFamily (fontFamilyIndex, &fontFamily);

**Comment by scheffle** [comment]
should be fixed with f82264f
