### ISSUE TITLE
Bundles vulnerable copy of Expat - please update to 2.2.1

### ISSUE THREAD

**Issue by hartwork** [steinbergmedia/vstgui#22]
Hi!

This repository [bundles an outdated vulnerable copy of Expat 2.1.1](https://github.com/steinbergmedia/vstgui/tree/master/vstgui/uidescription/expat). Please update your copy to version 2.2.1 with the latest security fixes. A change log with details is available at https://github.com/libexpat/libexpat/blob/master/expat/Changes . Thank you!

Best

&nbsp;
Sebastian

**Comment by scheffle** [comment]
Thanks for the report, see #23.
