### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [steinbergmedia/vstgui#264]

**Comment by scheffle** [comment]
Please provide a description of what you did and what you expect. The title "project doesn't install anything" just doesn't make sense as this project has no installer at all.

**Comment by yurivict** [comment]
```make install``` fails because there is no ```install``` target.
And there is no ```install``` target because cmake scripts have no ```install``` instructions.

**Comment by scheffle** [comment]
Correct. There's nothing to install at the moment.

**Comment by yurivict** [comment]
No libraries, no headers? How can one use it then?
