### ISSUE TITLE
Reintroduce setBackOffset() / getBackOffset() and respect the backOffset in all views / controls

### ISSUE THREAD

**Issue by raygit83** [steinbergmedia/vstgui#266]
The setBackOffset() / getBackOffset() API has recently been removed altogether. Since we're using this feature in various plugins I'd like to request them being re-added to all view / control implementations and the backOffset to be respected in the draw() implementations.

Thanks.

**Comment by raygit83** [comment]
Just to clarify: One is expected to select different slices of a MultiFrameBitmap by selecting different ranges using MultiFrameBitmapView::setMultiFrameBitmapRange() ?

**Comment by scheffle** [comment]
Correct. Do you see any problems with it?

**Comment by raygit83** [comment]
No no, not at all. I just wanted to make sure I'm getting things right. One thing though: Quickly reviewing the code it seems to me that the inverse mode indices might be off by 1 again, but I might be wrong...just really quickly reviewed the respective commit.

I know you're a busy man, Arne, but did you have a chance to check my minimal example demonstrating the AUv2 wrapper crash with the latest SDK version: https://forums.steinberg.net/t/crash-in-auv2-wrapper-using-vst3-sdk-v3-7-7/838542/4 ?
