### ISSUE TITLE
Bitmap drawing glitches in 4.5 on Mac OS with Retina displays

### ISSUE THREAD

**Issue by raygit83** [steinbergmedia/vstgui#28]
I have tried the recently released 4.5 update of VSTGUI. Everything seems to work fine so far except for bitmap drawing on Mac OS when running on a Retina display and the CFrame::setZoom() is set to anything != 1.0 (see image below). The example contains a CAnimKnob and the CFrame zoom is set to a value <1.The black border sometimes appears on the left, sometimes on the top or bottom or on both edges of the bounding box. The control itself is positioned on integral coordinates and has integral and even dimensions when created. The described behaviour can be reproduced in 10.11 and 10.12, but probably also affects older versions of Mac OS.

I was diff'ing lib/platform/mac/cgdrawcontext.cpp against the 4.3 revision and had the impression that it might have to do something with line 621 in CGDrawContext::drawBitmap() where the integralOffset argument for beginCGContext() was changed to true. But alas that didn't help.

It also doesn't make any difference whether the bitmap sits in a layered or non layered view container, except for the erroneousthe border being drawn in white instead of black when layered.

<img width="148" alt="knob" src="https://user-images.githubusercontent.com/22492388/28467466-4fcb2c40-6e30-11e7-92b0-48db1afc9314.png">

**Comment by scheffle** [comment]
Can you provide us with an example bitmap ?

**Comment by raygit83** [comment]
A sample screenshot is attached above. The same one can be found on the sdk.steinberg.net vstgui board.

Or do you mean the bitmap I'm using for the CAnimKnob? If so, any PNG with transparency will do. The CAnimKnob is embedded in a CLayeredViewContainer/CViewContainer that sits on my CFrame if that makes a difference.

**Comment by scheffle** [comment]
So it needs to be a PNG with transparency ? This was not stated in the first post. Attaching an example would help to track it down.

**Comment by raygit83** [comment]
Sorry I wasn't able to reply earlier, I just returned from my holidays. An example bitmap can be found here: http://s390174849.online.de/GainKnob.png

I haven't really investigated whether transparency makes a difference since all of my graphics (except for the background) use the alpha channel.

Here's the corresponding code snippet used in my editor's open function:

...
CRect size(0, 0, hBackground->getWidth(), hBackground->getHeight());

CLayeredViewContainer *container = new CLayeredViewContainer(size);
container->setBackground(hBackground);

auto hGainKnob = owned(new CBitmap("GainKnob.png"));
hGainKnob->getPlatfromBitmap()->setScaleFactor(2.0);

size(0, 0, hGainKnob->getWidth(), hGainKnob->getHeight() / 101);
size.offset(174 - hGainKnob->getWidth() / 2, 79 - hGainKnob->getHeight() / 101 / 2);
size.makeIntegral();
CAnimKnob *control = new CAnimKnob(size, this, kGainTag, hGainKnob);
container->addView(control);

frame->addView(container);

frame->setZoom(0.8); // <-- Works okay, when zoomFactor == 1.0
...

**Comment by scheffle** [comment]
Please check again with the latest vstgui sources. I think that this should be fixed now. Thanks for contributing.

**Comment by raygit83** [comment]
Yes, I can confirm that it has been fixed. Thanks!
