### ISSUE TITLE
Unhandled exception when using vstgui

### ISSUE THREAD

**Issue by justdanpo** [steinbergmedia/vstgui#288]
Hello.
I've tried buliding plugins which use `vstgui`. One of them is generated by `vst3projectgenerator`, another - `VST_SDK\my_plugins\helloworld_with_VSTGUI`. They work fine when built with debug configuration and both cause DAWs crashes (Ableton, FL) when bulit with release. `editorhost` and `VST3PluginTestHost` execute these plugins well.

vst sdk 3.7.7, vstgui 4.12

I've added debug logging and found this:
```
!initialized pimpl (CFrame::CFrame)	
!uninitialized pimpl (CFrame::beforeDelete)	
!null pimpl in VSTGUI::CFrame::invalidRect //invalid memory access
```
`beforeDelete()` is called from `VST3Editor::open`
```
	if (!enableEditing (false))
	{
		getFrame ()->forget ();
		return false;
	}
```

**Comment by justdanpo** [comment]
Ooook, this happens when not full plugin bundle is installed (no .uidesc file available in resources path) which is surely bad, but crashing DAW isn't good either.

**Comment by scheffle** [comment]
Thanks for the report. And you're right, it should not crash.
