### ISSUE TITLE
Segment Button segment names string gets replaced by parameter steps normalized value in Release build

### ISSUE THREAD

**Issue by rodv92** [steinbergmedia/vstgui#297]
How to reproduce :

In my case the segment button uses 5 segments.
Insert segment button using VSTGUI WYSIWYG Editor
Define segment names with arbitrary tags, ex: Setting1,Setting2,Setting3,Setting4,Setting5. with total number of settings corresponding to the number of segments.
link control tag to a parameter with a stepcount of 5.
Save and Reload editor, or even Save and reload plugin. Segment Names display is ok, that is : Setting1,Setting2,Setting3,Setting4,Setting5

Build project in release. Seems that VST_GUI_LIVE_EDITING=0 is implicit in release builds.
Launch the plugin, Segment Button names in the GUI now show parameter steps : 0.20 0.40, 0.60, 0.80, 1.00 instead of tags.

What is strange is that when going back to Debug build the problem remains.
The uidesc file in the filesystem has not changed and has the correct segment names, as well as in the code resource.

Unless it is unproper use of SegmentButton from my part, it seems like a bug.

**Comment by scheffle** [comment]
Hi, is this in combination with the VST3Editor from the VST3 SDK? Then the segment button gets the names of the segments from the parameter. Please use a StringListParameter and add the names to the parameter and then link this parameter to the segment button.
Does this solve your issue?

**Comment by rodv92** [comment]
Thank you for the information. I will try.

**Comment by rodv92** [comment]
It works thank you ! Used the note_expression_synth_controller.cpp sample code for anyone that has the same issue.
