### ISSUE TITLE
Font drawing inconsistencies between Mac and Windows

### ISSUE THREAD

**Issue by bxjoscha** [steinbergmedia/vstgui#298]
VSTGUI has the following two font drawing inconsistencies between Mac and Windows:
- On Mac, fonts are drawn thicker and smoother than on Windows
- On Windows, the anti-aliasing is not mono-chromatic as it is on Mac, but coloured

The following drawings are made with the current develop state of VSTGUI using the Hello World example app.

![VSTGUI Font Drawing Inconsistencies](https://user-images.githubusercontent.com/110902747/236156974-a58bd262-06e3-462b-8c75-b719e8c7b3f1.png)

In the above image, the first image is not scaled correctly, so here again:

![VSTGUI Font Drawing Inconsistencies 2](https://user-images.githubusercontent.com/110902747/236160309-2dae57e3-3863-45d7-8e7e-d84330db5921.png)

**Comment by bxjoscha** [comment]
I just realized that my example image is squashed. The Mac "Hello World!" text is slight zoomed versus the Windows text.

**Comment by scheffle** [comment]
Hi, this is the difference between the platform dependent font render engines. If you need pixel perfect text rendering then you should pre-render the text into bitmaps and use them instead. Or do you have any other idea how this could be done?

**Comment by bxjoscha** [comment]
Hi @scheffle, actually I was able to fix both issues in our internal VSTGUI fork that, unfortunately, is not up-to-date to the current VSTGUI state. Here are the two changes I have made internally (still need to be validated by our QA, but on my machine it worked).

Actually, that part of the code changed and I do not find the lines in the latest state of VSTGUI.

![Screenshot 2023-05-05 at 07 07 42](https://user-images.githubusercontent.com/110902747/236381512-22b2f3f0-6c0c-4c6a-85a0-7f63bf1c66d5.png)

![Screenshot 2023-05-05 at 07 08 02](https://user-images.githubusercontent.com/110902747/236381520-69f186cb-1697-4974-bf95-5fe3d7f36545.png)

**Comment by bxjoscha** [comment]
I found the lines the current VSTGUI version as well:

https://github.com/steinbergmedia/vstgui/blob/develop/vstgui/lib/platform/mac/coregraphicsdevicecontext.mm#L904

https://github.com/steinbergmedia/vstgui/blob/develop/vstgui/lib/platform/win32/direct2d/d2dgraphicscontext.cpp#L845

**Comment by bxjoscha** [comment]
If the fix gets validated, I would create a PR, but you could also investigate already and perhaps you are happy changing the code by yourself already.

**Comment by scheffle** [comment]
Hi @bxjoscha , I'm very busy at the moment, but I will take care of this in the coming weeks.
