### ISSUE TITLE
forum subscription not working / documentation outdated

### ISSUE THREAD

**Issue by rhavin** [steinbergmedia/vstgui#30]
Subscribing to sdk.steinberg.net does not work (no one seems to care activating accounts since a week?)

The documentation has little hints about working with VSTGUI4 / VST3, Most acticles are about 2.4 and dont work this way in VST3, most classes in VSTGUI4 dont even have a single sentence describing *what* they are used for.

For example:
- *how* do I setup a listener for a button in VST3/GUI4 when the button comes from XML?
- how can I get a CControl* from a tag inside my controller?

**Comment by scheffle** [comment]
It seems you were able to subscribe to the forum, so I close this one.
