### ISSUE TITLE
Conditional use of Windows 8.1 dpi functions?

### ISSUE THREAD

**Issue by jpcima** [steinbergmedia/vstgui#41]
Hello. To further the mingw compatibility effort I have tried to get the standalone target to compile. I have found two blocking elements absent in mingw, the dpi-related functions, and the PPL concurrency library.

MinGW currently has 2 missing APIs, *GetDpiForMonitor* and *SetProcessDpiAwareness*, regardless of the value _WIN32_WINNT. So I have a question here: for these functions MSDN claims support only since Windows 8.1, so wouldn't it be wiser to dynamically resolve these functions, and use conditionally?

I'm thinking of this as the approach for mingw, but it may also be relevant to VSTGUI globally since the readme page indicates support of Windows 7. Any opinion on this?

**Comment by scheffle** [comment]
Hi,
the standalone target has a different support target than the vstgui library. See  vstgui/standalone/include/doc.h.
Windows 7 is just not supported an there are no plans to do so.
