### ISSUE TITLE
TOOLS_for_UR242_V104_Mac Installation Failed in MacOS High Sierra

### ISSUE THREAD

**Issue by opp100** [steinbergmedia/vstgui#50]
Hey there,

I don't know where should I post this issue. I post this in Steinberg forum, but there are no one reply since Dec. Thus I came here to post this issue. 

I try to install the tool for UR242 in my MacBook. I following the instruction from the Steinberg website, and tried most of the solutions. I have tried that allow the security stuff from the System Preference, run install from sudo, using chmod give 755 permission, it alway failed to install.

I dumped the log fro installer. 
```
Jan 16 22:11:53 Youke-MacbookPro installd[540]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “TOOLS for UR242 V1.0.4.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/youke/Desktop/TOOLS_for_UR242_V104_Mac/TOOLS%20for%20UR242%20V1.0.4.pkg#eLicenserControlProxy.pkg, PKInstallPackageIdentifier=com.yamaha.pkg.eLicenserControlProxy, NSLocalizedDescription=An error occurred while running scripts from the package “TOOLS for UR242 V1.0.4.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cTOOLS for UR242 V1.0.4.pkg\U201d.";
	    NSURL = "file://localhost/Users/youke/Desktop/TOOLS_for_UR242_V104_Mac/TOOLS%20for%20UR242%20V1.0.4.pkg#eLicenserControlProxy.pkg";
	    PKInstallPackageIdentifier = "com.yamaha.pkg.eLicenserControlProxy";
	}
Jan 16 22:11:54 Youke-MacbookPro Installer[535]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Jan 16 22:11:54 Youke-MacbookPro Installer[535]: Displaying 'Install Failed' UI.
Jan 16 22:11:54 Youke-MacbookPro Installer[535]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```

It seems like `com.yamaha.pkg.eLicenserControlProxy` fail to install, and I try to manually run the eLicenserControlSetup, after enter the username and password, nothing really happen. 

If there are any one can help me install that, that will be appreciate.

###The Machine Info###
MacBook Pro (15-inch, 2017) 
2.9 GHz Intel Core i7
16 GB 2133 MHz LPDDR3

If there are anyone can help me on that. it will be cool.

**Comment by scheffle** [comment]
Please get in touch with your local dealer, this is a development tool not meant for users.
