### ISSUE TITLE
Option menu multiple check style wrong on Windows

### ISSUE THREAD

**Issue by bxjoscha** [steinbergmedia/vstgui#51]
Option menus with multiple check style behave differently on Windows and Mac. On Mac it behaves as expected, but on Windows the current index is always checked. This behaviour is expected for the standard check style, but not for multiple check style. I have fixed this issue in `win32optionmenu.cpp` in the function `Win32OptionMenu::createMenu()`.

Instead of writing
`if (_menu->getStyle () & kCheckStyle && inc == _menu->getCurrentIndex ()) flags |= MF_CHECKED;`
it should be
`if (_menu->getStyle () & kCheckStyle && inc == _menu->getCurrentIndex () && !(multipleCheck && !item->isChecked ())) flags |= MF_CHECKED;`

This looks strange, but it becomes clear when you look at the definition of the flag `kMultipleCheckStyle`, which is defined as the number 1025, which is 10000000001. This is a strange definition for a bit flag.

Another way to fix this is to redefine the flag `kMultipleCheckStyle`, such that it is a power of 2.

**Comment by scheffle** [comment]
Can you please make a pull request with the proposed fix. I cannot find the line which should be changed in the current source.

**Comment by bxjoscha** [comment]
Yes, eventually I have opened a new pull request for commit #53.

**Comment by ygrabit** [comment]
this will be fixed in the next update coming soon, Thx

**Comment by bxjoscha** [comment]
Cool, thx.
