### ISSUE TITLE
Mac tutorial doesn't compile

### ISSUE THREAD

**Issue by esp1** [steinbergmedia/vstgui#57]
I'm trying to use the latest vstgui 4.5 release, but can't get the mac Xcode tutorial to compile. I was able to get around some of the issues:
* vstsdk2.4 was missing, so I added that
* I set some compiler flags for C++11 support in the Build Settings
But even after that I started encountering code issues in the tutorial - class names and constructor parameters have changed. At this point I decided to give up and ask if someone in the know could please update the tutorial code so that it works :-) I'm very new to vstgui so I need some working example code to help me use it... ^_^

**Comment by ygrabit** [comment]
Did you try to compile Again plugin from the VST3 SDK, this one use's VSTGUI too?

**Comment by esp1** [comment]
Yes, my colleague tried compiling the tutorial in VST 3 and ran into the same issues.

**Comment by scheffle** [comment]
The tutorial in the vstgui directory is obsolete. Please use the VST3 examples as a starting point.
