### ISSUE TITLE
win32frame exception when pressing left and right keys

### ISSUE THREAD

**Issue by avocadoboi** [steinbergmedia/vstgui#58]
When the plugin is focused and no onKeyDown event is handled, the whole thing crashes. I'm using FL Studio as the host, and I don't know if this bug is specific to it. It's an "access violation reading location 0xFFFFFFFFFFFFFFFF" exception and occurs at line 985 of win32frame.cpp. It happens when the keydown event makes FL Studio close the editor to open an options tab in the wrapper, when the frame is about to call pFrame->platformOnActivate(false). This crash even happens with the VST SDK example projects, so it doesn't have anything to do with my specific implementation. I don't want people to lose their project just because they pressed a key :^(

**Comment by scheffle** [comment]
Hi avocadoboi,
I'm unable to reproduce this issue.
Can you provide a step-by-step instruction on how to reproduce this ?
Note that I'm not familiar with FL-Studio so make this instruction as detailed as possible.
