### ISSUE TITLE
CTextEdit can show different font when editing vs. when displaying

### ISSUE THREAD

**Issue by Ry-Fi** [steinbergmedia/vstgui#79]
Example: On Windows, "OCR A Extended" is an included font.  If you create a font definition in the XML that uses "OCR A Extended" and assign that font to a CTextEdit, the result is that it doesn't work when **displaying** the CTextEdit and the default font is used instead, but when **editing** in the CTextEdit, the control suddenly switches to the correct OCR font.  In the reverse situation, shortening it to just "OCR A" results in the intended font being used when **displaying**, but not when **editing**.

There's evidently a conflicting difference between how the Win32TextEdit and the CParamDisplay identify fonts by name.

**Comment by scheffle** [comment]
Should be fixed with f82264f
