### ISSUE TITLE
Call to cairo_xcb_surface_create crashes on re-opening editor.

### ISSUE THREAD

**Issue by rehans** [steinbergmedia/vstgui#80]
Hey,

I stress-tested the AGain.vst3 editor on Linux with Reaper and Bitwig Studio and quickly ran into a crash after closing and re-opening the editor several times. The crash happens on calling cairo_xcb_surface_create ([click here](https://github.com/steinbergmedia/vstgui/blob/master/vstgui/lib/platform/linux/x11frame.cpp#L126)).

Before the crash I get an output: 
reaper: ../../../../src/cairo-xcb-screen.c:219: _get_screen_index: Assertion `!"reached"' failed.

I searched that on google and found a post by @abique here:
https://lists.cairographics.org/archives/cairo/2017-December/028496.html

So I did what was suggested and extended the ctor of `DrawHandler` by 

```
(device is a member of DrawHandler)
device = cairo_device_reference(cairo_surface_get_device(surface));
```

and created a dtor `~DrawHandler` with

```
cairo_device_finish(device);
cairo_device_destroy(device);
```

Afterwards the crash is gone. Maybe @abique can share his experience. Is this still used in u-he plug-ins?

(I also found this which is doing something very similar: https://chromium.googlesource.com/chromiumos/third_party/cairo/+/f9344911250ea347fb0eb54d7ab1f97c8f685a20/boilerplate/cairo-boilerplate-xcb.c)

Any more ideas?

René

**Comment by abique** [comment]
Hi,

In u-he we use cairo image now plus xcb-shm to quickly upload the pixmap to the xserver.
I stopped using cairo-xcb because it has some global variables or caches that I wanted to avoid.
Yes you have to do the ref-counting right.

Regards,
Alex

**Comment by scheffle** [comment]
Fixed on the develop branch

**Comment by myrrc** [comment]
Related: https://github.com/sfztools/sfizz-ui/issues/136
