### ISSUE TITLE
Static analysis report

### ISSUE THREAD

**Issue by shlyakpavel** [steinbergmedia/vstgui#81]
Hello. Thanks for bringing this to linux!
Have finally checked some parts with a static analysis tool. Here are some points I've found
1. The 'inputBitmap' pointer was utilized before it was verified against nullptr.
https://github.com/steinbergmedia/vstgui/blob/f6b70f7227604a6ce80abed4b87c3d2ae9a9e7dc/vstgui/lib/cbitmapfilter.cpp#L412-L413
2. Expression is always true
https://github.com/steinbergmedia/vstgui/blob/f6b70f7227604a6ce80abed4b87c3d2ae9a9e7dc/vstgui/lib/cframe.cpp#L323
3. Typo?
https://github.com/steinbergmedia/vstgui/blob/f6b70f7227604a6ce80abed4b87c3d2ae9a9e7dc/vstgui/lib/controls/ctextlabel.cpp#L326-L328
4. Why?
https://github.com/steinbergmedia/vstgui/blob/master/vstgui/uidescription/uiviewcreator.cpp#L1511
https://github.com/steinbergmedia/vstgui/blob/master/vstgui/uidescription/uiviewcreator.cpp#L1521
5. The same here
https://github.com/steinbergmedia/vstgui/blob/master/vstgui/uidescription/uiviewcreator.cpp#L1506
https://github.com/steinbergmedia/vstgui/blob/master/vstgui/uidescription/uiviewcreator.cpp#L1516
6. One pair of parentheses is unnecessary or misprint is present.
https://github.com/steinbergmedia/vstgui/blob/master/vstgui/uidescription/uiviewcreator.cpp#L2856
https://github.com/steinbergmedia/vstgui/blob/master/vstgui/uidescription/uiviewcreator.cpp#L2871
7. Consider inspecting the '?:' operator. A temporary object of the 'SharedPointer' type is being created and subsequently destroyed. Check third operand.
https://github.com/steinbergmedia/vstgui/blob/f6b70f7227604a6ce80abed4b87c3d2ae9a9e7dc/vstgui/uidescription/editing/uibitmapscontroller.cpp#L117

**Comment by shlyakpavel** [comment]
Have left PRs
1. https://github.com/steinbergmedia/vstgui/pull/84
2. https://github.com/steinbergmedia/vstgui/pull/83
3. Not yet
4. Not yet
5. Not yet
6. https://github.com/steinbergmedia/vstgui/pull/82
7. Not yet

**Comment by scheffle** [comment]
Thanks, please make one github issue per static analysis issue. That's easier to track. And please see the develop branch, there should be some fixes already.
