### ISSUE TITLE
Missing header file editoruidesc.h when building VSTGUI on Alpine Linux

### ISSUE THREAD

**Issue by anerss** [steinbergmedia/vstgui#87]
The editoruidesc.h header file is not created when building on [Alpine Linux](https://www.alpinelinux.org/).

    [ 89%] Building CXX object _deps/vstsdk-build/vstgui4/vstgui/uidescription/CMakeFiles/vstgui_uidescription.dir/editing/uieditmenucontroller.cpp.o
    /build/_deps/vstsdk-src/vstgui4/vstgui/uidescription/editing/uieditcontroller.cpp:50:10: fatal error: editoruidesc.h: No such file or directory
     #include "editoruidesc.h"
              ^~~~~~~~~~~~~~~~
    compilation terminated.

The `execute_process` in vstgui4/vstgui/uidescription/CMakeLists.txt fails with RESULT_VARIABLE='Exec format error' because of a bug in the createuidescdata.sh script.  
The first line in createuidescdata.sh should be ```#!/bin/bash``` not ```# /bin/bash```.

**Comment by scheffle** [comment]
fixed on the develop branch
