### ISSUE TITLE
Checkmarks in submenu under windows.

### ISSUE THREAD

**Issue by sagantech** [steinbergmedia/vstgui#92]
On mac this apparently works fine but under windows no checkmark appears. I suggest the following change to fix this. win32optionmenu.cpp starting at line 171:
			if (item->getSubmenu ())
			{
				HMENU submenu = createMenu (item->getSubmenu (), offsetIdx);
				if (submenu)
				{
					if (multipleCheck && item->isChecked ())
						flags |= MF_CHECKED;
					AppendMenu (menu, flags|MF_POPUP|MF_ENABLED, (UINT_PTR)submenu, (const TCHAR*)entryText);
				}
			}

**Comment by scheffle** [comment]
Fixed with #96
